import type { Capability } from './capabilities.js';

export interface BusinessTypeConfig {
  readonly label: string;
  readonly icon: string;
  readonly capabilities: ReadonlyArray<Capability>;
}

export const BUSINESS_TYPES = {
  ferreteria_construccion:    { label: 'Ferretería y construcción',    icon: '🔧', capabilities: ['catalog','cart_orders','payments','delivery'] },
  papeleria_libros:           { label: 'Papelería y libros',           icon: '📝', capabilities: ['catalog','cart_orders','payments','delivery'] },
  licoreria:                  { label: 'Licorería',                    icon: '🍷', capabilities: ['catalog','cart_orders','payments','delivery'] },
  ropa_calzado:               { label: 'Ropa y calzado',               icon: '👗', capabilities: ['catalog','cart_orders','payments','delivery'] },
  articulos_belleza:          { label: 'Artículos de belleza',         icon: '💄', capabilities: ['catalog','cart_orders','payments','delivery'] },
  tienda_barrio:              { label: 'Tienda de barrio',             icon: '🏪', capabilities: ['catalog','cart_orders','delivery'] },
  minimercado:                { label: 'Minimercado',                  icon: '🛒', capabilities: ['catalog','cart_orders','payments','delivery'] },
  electronica_informatica:    { label: 'Electrónica e informática',    icon: '💻', capabilities: ['catalog','cart_orders','payments','delivery','quotes'] },
  articulos_hogar:            { label: 'Artículos para el hogar',      icon: '🏠', capabilities: ['catalog','cart_orders','payments','delivery'] },
  articulos_deportivos:       { label: 'Artículos deportivos',         icon: '⚽', capabilities: ['catalog','cart_orders','payments','delivery'] },
  tienda_mascotas_vet:        { label: 'Tienda de mascotas/vet',       icon: '🐾', capabilities: ['catalog','cart_orders','payments','delivery','appointments'] },
  farmacia_drogueria:         { label: 'Farmacia y droguería',         icon: '💊', capabilities: ['catalog','cart_orders','payments','delivery'] },
  tienda_naturista:           { label: 'Tienda naturista',             icon: '🌿', capabilities: ['catalog','cart_orders','payments','delivery'] },
  carniceria:                 { label: 'Carnicería',                   icon: '🥩', capabilities: ['catalog','cart_orders','payments','delivery'] },
  salsamentaria:              { label: 'Salsamentaria',                icon: '🧀', capabilities: ['catalog','cart_orders','payments','delivery'] },
  accesorios_bisuteria:       { label: 'Accesorios y bisutería',       icon: '💍', capabilities: ['catalog','cart_orders','payments','delivery'] },
  tienda_regalos:             { label: 'Tienda de regalos',            icon: '🎁', capabilities: ['catalog','cart_orders','payments','delivery'] },
  distribuidora_mayorista:    { label: 'Distribuidora / Mayorista',    icon: '📦', capabilities: ['catalog','cart_orders','payments','delivery','quotes'] },
  insumos_agropecuarios:      { label: 'Insumos agropecuarios',        icon: '🌾', capabilities: ['catalog','cart_orders','payments','delivery','quotes'] },
  articulos_automotrices:     { label: 'Artículos automotrices',       icon: '🔩', capabilities: ['catalog','cart_orders','payments','quotes'] },
  venta_automoviles:          { label: 'Venta de automóviles',         icon: '🚗', capabilities: ['catalog','quotes','appointments','payments'] },
  restaurante_comida_rapida:  { label: 'Restaurante / comida rápida',  icon: '🍔', capabilities: ['catalog','cart_orders','payments','delivery','reservations'] },
  cafeteria:                  { label: 'Cafetería',                    icon: '☕', capabilities: ['catalog','cart_orders','payments'] },
  bar:                        { label: 'Bar',                          icon: '🍸', capabilities: ['catalog','reservations','payments'] },
  panaderia_reposteria:       { label: 'Panadería y repostería',       icon: '🥐', capabilities: ['catalog','cart_orders','payments','delivery'] },
  estetica_salud:             { label: 'Estética y salud',             icon: '💆', capabilities: ['catalog','appointments','payments'] },
  tatuajes_piercings:         { label: 'Tatuajes y piercings',         icon: '🎨', capabilities: ['catalog','appointments','payments'] },
  reparaciones_mantenimiento: { label: 'Reparaciones y mantenimiento', icon: '🔧', capabilities: ['appointments','quotes','payments'] },
  taller_automotriz:          { label: 'Taller automotriz',            icon: '🔧', capabilities: ['appointments','quotes','payments'] },
  salon_belleza_barberia:     { label: 'Salón de belleza / Barbería',  icon: '💇', capabilities: ['catalog','appointments','payments'] },
  spa_bienestar:              { label: 'Spa y bienestar',              icon: '🧖', capabilities: ['catalog','appointments','reservations','payments'] },
  abogado_juridico:           { label: 'Abogado / Servicios jurídicos', icon: '⚖️', capabilities: ['catalog','appointments','quotes','payments'] },
  arquitecto:                 { label: 'Arquitecto',                    icon: '📐', capabilities: ['catalog','appointments','quotes','payments'] },
  ingeniero_civil:            { label: 'Ingeniero civil',               icon: '🏗️', capabilities: ['appointments','quotes','payments'] },
  ingeniero_sistemas:         { label: 'Ingeniero de sistemas',         icon: '💻', capabilities: ['catalog','appointments','quotes','payments'] },
  contador_contabilidad:      { label: 'Contador / Auditoría',          icon: '📊', capabilities: ['catalog','appointments','quotes','payments'] },
  consultoria_empresarial:    { label: 'Consultoría empresarial',       icon: '💼', capabilities: ['catalog','appointments','quotes','payments'] },
  medico_general:             { label: 'Médico general',                icon: '🩺', capabilities: ['catalog','appointments','payments'] },
  odontologo:                 { label: 'Odontólogo / Clínica dental',   icon: '🦷', capabilities: ['catalog','appointments','payments'] },
  psicologo:                  { label: 'Psicólogo',                     icon: '🧠', capabilities: ['appointments','payments'] },
  fisioterapeuta:             { label: 'Fisioterapeuta',                icon: '🏥', capabilities: ['catalog','appointments','payments'] },
  nutricionista:              { label: 'Nutricionista',                 icon: '🥗', capabilities: ['catalog','appointments','payments'] },
  veterinario:                { label: 'Veterinario',                   icon: '🐾', capabilities: ['catalog','appointments','payments','cart_orders'] },
  optometra:                  { label: 'Optómetra / Óptica',            icon: '👓', capabilities: ['catalog','appointments','payments','cart_orders'] },
  laboratorio_clinico:        { label: 'Laboratorio clínico',           icon: '🔬', capabilities: ['catalog','appointments','payments'] },
  agente_inmobiliario:        { label: 'Bienes raíces',                 icon: '🏡', capabilities: ['catalog','appointments','quotes','payments'] },
  agente_seguros:             { label: 'Agente de seguros',             icon: '🛡️', capabilities: ['catalog','appointments','quotes','payments'] },
  notaria:                    { label: 'Notaría',                       icon: '📜', capabilities: ['catalog','appointments','quotes','payments'] },
  diseno_grafico:             { label: 'Diseño gráfico',                icon: '🎨', capabilities: ['catalog','quotes','payments'] },
  fotografia_video:           { label: 'Fotografía y video',            icon: '📸', capabilities: ['catalog','appointments','quotes','payments'] },
  coaching_mentoria:          { label: 'Coaching / Mentoría',           icon: '🎯', capabilities: ['catalog','appointments','payments'] },
  traductor_interprete:       { label: 'Traductor / Intérprete',        icon: '🌐', capabilities: ['catalog','quotes','payments'] },
  cerrajeria:                 { label: 'Cerrajería',                    icon: '🔑', capabilities: ['catalog','appointments','quotes','payments'] },
  fumigacion_plagas:          { label: 'Fumigación / Plagas',           icon: '🐛', capabilities: ['catalog','appointments','quotes','payments'] },
  aseo_limpieza:              { label: 'Aseo y limpieza',               icon: '🧹', capabilities: ['catalog','appointments','quotes','payments'] },
  plomeria:                   { label: 'Plomería',                      icon: '🔧', capabilities: ['appointments','quotes','payments'] },
  mudanzas_trasteos:          { label: 'Mudanzas y trasteos',           icon: '📦', capabilities: ['quotes','payments'] },
  marketing_publicidad:       { label: 'Marketing y publicidad',        icon: '📢', capabilities: ['catalog','quotes','appointments','payments'] },
  servicios_educativos:       { label: 'Servicios educativos',          icon: '📚', capabilities: ['catalog','appointments','payments'] },
  academia_idiomas:           { label: 'Academia de idiomas',           icon: '🗣️', capabilities: ['catalog','appointments','payments'] },
  tutor_clases_particulares:  { label: 'Tutor / Clases particulares',   icon: '📖', capabilities: ['catalog','appointments','payments'] },
  hoteles_turismo:            { label: 'Hoteles y turismo',             icon: '🏨', capabilities: ['catalog','reservations','payments'] },
  organizacion_eventos:       { label: 'Organización de eventos',       icon: '🎉', capabilities: ['catalog','quotes','reservations','payments'] },
  gimnasio:                   { label: 'Gimnasio',                      icon: '🏋️', capabilities: ['catalog','appointments','payments'] },
  entretenimiento_ocio:       { label: 'Entretenimiento y ocio',        icon: '🎮', capabilities: ['catalog','reservations','payments'] },
  escuela_danza:              { label: 'Escuela de danza',              icon: '💃', capabilities: ['catalog','appointments','payments'] },
  escuela_musica:             { label: 'Escuela de música',             icon: '🎵', capabilities: ['catalog','appointments','payments'] },
  industria_manufactura:      { label: 'Industria / manufactura',       icon: '🏭', capabilities: ['catalog','quotes','payments'] },
  transporte_logistica:       { label: 'Transporte y logística',        icon: '🚚', capabilities: ['quotes','payments'] },
  prestamos_financiamiento:   { label: 'Préstamos y financiamiento',    icon: '💰', capabilities: ['appointments','quotes'] },
  otro:                       { label: 'Otro',                          icon: '🏢', capabilities: ['catalog','payments'] },
} as const satisfies Record<string, BusinessTypeConfig>;

export type BusinessType = keyof typeof BUSINESS_TYPES;
